@HOST = http://localhost:9000/api/v1

# AUTHENTICATION
# @name Auth_Register
POST {{HOST}}/managers HTTP/1.1
Content-Type: application/json

{
    "firstName": "example2",
    "lastName": "example2",
    "email": "example2@gmail.com",
    "password": "example"
}
###
# @name Auth_Login
POST {{HOST}}/auth HTTP/1.1
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "example"  
}
###
# @name Store_Select
POST {{HOST}}/auth/select-store HTTP/1.1
Content-Type: application/json

{
    "storeId": "293f022e-9b45-47b4-824c-063e4cdfe719"
}
###

# STORE
# @name Store_Create
POST {{HOST}}/stores HTTP/1.1
Content-Type: application/json

{
    "name": "rei dos salgados 2"
}
###
# @name Store_GetAll
GET {{HOST}}/stores HTTP/1.1
###

# MANAGERS
# @name Manager_FindWithStores
GET {{HOST}}/managers HTTP/1.1
###
# @name Manager_GetInformations
GET {{HOST}}/managers/my-informations HTTP/1.1
###

# PRODUCTS
# @name Product_Create
POST {{HOST}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "produto01",
    "description": "description01",
    "storeId": "293f022e-9b45-47b4-824c-063e4cdfe719" 
    
}
###
# @name Product_FindAll
GET {{HOST}}/products HTTP/1.1
###
PATCH {{HOST}}/products/01f374d7-4882-4c78-9ea0-fbbfd5493e36 HTTP/1.1
Content-Type: application/json

{
  "name": "example",
  "description": "example",
  "quantity": "3",
  "price": "3",
  "categories": [
    {
      "id": "c001dbad-cfe0-4289-9464-591035da8487",
      "name": "teste",
      "storeId": "293f022e-9b45-47b4-824c-063e4cdfe719"
    }
  ],
  "productTipics": []
}
###

# CATEGORIES
# @name Category_Create
POST {{HOST}}/categories HTTP/1.1
Content-Type: application/json

{
    "name": "teste"
}

###
# @name Category_FindAll
GET {{HOST}}/categories HTTP/1.1

###
# PRODUCT TOPICS
# @name ProductTopic_Create
POST {{HOST}}/product-topics HTTP/1.1
Content-Type: application/json

{
    "name": "Que tal mais molho?",
    "productId": "01f374d7-4882-4c78-9ea0-fbbfd5493e36"
}
###
# @name @ProductTopic_Update
PATCH {{HOST}}/product-topics/293f022e-9b45-47b4-824c-063e4cdfe719
Content-Type: application/json

[
    {
        "id": "teste",
        "name": "teste"
    }
]


###
# TOPIC OPTIONS
POST {{HOST}}/topic-options HTTP/1.1
Content-Type: application/json

{
    "name": "teste",
    "price": 20,
    "id": "teste"
}