@HOST = http://localhost:8000

# @name index
GET {{HOST}}/ HTTP/1.1
###
#
POST {{HOST}}/clients HTTP/1.1
Content-Type: application/json

{
    "name": "victor",
    "email": "example@gmail.com",
    "password": "example"
}

### 
POST {{HOST}}/auth HTTP/1.1
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "example"
}

###
GET {{HOST}}/stores HTTP/1.1